### ISSUE TITLE
Host cucumber feature files as Zip on page

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-website-old#40]
It would be a nice quality of life thing if you guys offered a link to the zip of cucmber features (e.g https://deepstream.io/tests/cucumber-features.zip or something similar). It would also make automated builds easier too since as a pre step it could just download those files and fail if a feature isn't correct.
May also worth thinking about how to handle changes to the specification(i.e this client is 1.0 compatible and uses cucumber-features-1.0.zip for testing) etc.

**Comment by yasserf** [comment]
I think if we use git submodules we might get a few more benefits.  We could use version tagging instead of keeping copies of each version hosted and trigger client builds automatically when the feature files change to ensure they still pass.

Regarding version vs features, that is complicated. You could get your cucumber runnner to only run features in certain folders and that way always incorporate the latest changes for the features you do support while ignoring changes in others.

**Comment by WolframHempel** [comment]
Not sure tbh. Downloading archived files is a common step in e.g. maven or make based buildsystems. Submodules on the other hand are always a bit messy which - I accept - might be due to us never using them right.

**Comment by yasserf** [comment]
Nice thing about using git would be that they wouldn't have to consider creating that sort of build differently per client, it could be a set of git commands that would apply consistently.

I do agree though that they aren't exactly the easiest thing to use, I have seen people muddle up the SHA reference quite often.
